services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  admin_microservice:
    build:
      context: ./admin_microservice
      dockerfile: Dockerfile
    container_name: admin_microservice
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
    volumes:
      - ./admin_microservice:/app