services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_ALLOW_GUEST_LOGIN=true
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysqldb_admin:
    image: mysql:latest
    container_name: mysqldb_admin
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - mysqldb_admin:/var/lib/mysql
      - ./init_db/init_admin_db.sql:/docker-entrypoint-initdb.d/init_admin_db.sql

  mongodb_auth:
    image: mongo:latest
    container_name: mongodb_auth
    ports:
      - "27019:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_INITDB_DATABASE=kea_cars_auth_dev
    volumes:
      - mongodb_auth:/data/db

  mongodb_customer:
    image: mongo:latest
    container_name: mongodb_customer
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_INITDB_DATABASE=kea_cars_customer_dev
    volumes:
      - mongodb_customer:/data/db

  mysqldb_employee:
    image: mysql:latest
    container_name: mysqldb_employee
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - mysqldb_employee:/var/lib/mysql
      - ./init_db/init_employee_db.sql:/docker-entrypoint-initdb.d/init_employee_db.sql

  seed_mongodb_auth:
    build:
      context: ./auth_microservice
      dockerfile: scripts/Dockerfile
    container_name: seed_mongodb_auth
    depends_on:
      - mongodb_auth
    environment:
      - MONGO_DB_HOST=mongodb_auth
      - MONGO_DB_PORT=27017
      - MONGO_DB_ROOT_USERNAME=root
      - MONGO_DB_ROOT_PASSWORD=rootpassword
      - MONGO_DB_NAME=kea_cars_auth_dev
      - MONGO_DB_APPLICATION_USERNAME=application_user
      - MONGO_DB_APPLICATION_PASSWORD=supersecretpassword

  seed_mongodb_customer:
    build:
      context: ./customer_microservice
      dockerfile: scripts/Dockerfile
    container_name: seed_mongodb_customer
    depends_on:
      - mongodb_customer
    environment:
      - MONGO_DB_HOST=mongodb_customer
      - MONGO_DB_PORT=27017
      - MONGO_DB_ROOT_USERNAME=root
      - MONGO_DB_ROOT_PASSWORD=rootpassword
      - MONGO_DB_NAME=kea_cars_customer_dev
      - MONGO_DB_APPLICATION_USERNAME=application_user
      - MONGO_DB_APPLICATION_PASSWORD=supersecretpassword

  admin_microservice:
    build:
      context: ./admin_microservice
      dockerfile: Dockerfile
    container_name: admin_microservice
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - mysqldb_admin
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - MYSQL_DB_HOST=mysqldb_admin
      - MYSQL_DB_PORT=3306
      - MYSQL_DB_ROOT_USERNAME=root
      - MYSQL_DB_ROOT_PASSWORD=rootpassword
      - MYSQ_DB_NAME=kea_cars_admin_dev
      - MYSQL_DB_APPLICATION_USERNAME=application_user
      - MYSQL_DB_APPLICATION_PASSWORD=supersecretpassword
    volumes:
      - ./admin_microservice:/app

  auth_microservice:
    build:
      context: ./auth_microservice
      dockerfile: Dockerfile
    container_name: auth_microservice
    ports:
      - "8001:8001"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8001
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - MONGO_DB_HOST=mongodb_auth
      - MONGO_DB_PORT=27017
      - MONGO_DB_ROOT_USERNAME=root
      - MONGO_DB_ROOT_PASSWORD=rootpassword
      - MONGO_DB_NAME=kea_cars_auth_dev
      - MONGO_DB_APPLICATION_USERNAME=application_user
      - MONGO_DB_APPLICATION_PASSWORD=supersecretpassword
    volumes:
      - ./auth_microservice:/app

  customer_microservice:
    build:
      context: ./customer_microservice
      dockerfile: Dockerfile
    container_name: customer_microservice
    ports:
      - "8002:8002"
    depends_on:
      - mongodb_customer
      - seed_mongodb_customer
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8002
      - MONGO_DB_HOST=mongodb_customer
      - MONGO_DB_PORT=27017
      - MONGO_DB_NAME=kea_cars_customer_dev
      - MONGO_DB_APPLICATION_USERNAME=application_user
      - MONGO_DB_APPLICATION_PASSWORD=supersecretpassword
    volumes:
      - ./customer_microservice:/app

volumes:
  mysqldb_admin:
  mongodb_auth:
  mongodb_customer:
  mysqldb_employee:
