apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki.default.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
      - job_name: system
        static_configs:
          - targets:
              - promtail:9080
            labels:
              job: varlogs
              __path__: /var/log/*.log

      - job_name: auth-microservice
        static_configs:
          - targets:
              - promtail:9080
            labels:
              job: auth-microservice
              __path__: /var/log/*.log
